- package-lock.json
- package.json
- src/app/data/environment.service.ts
correct timestamp for availability from hh to HH
Bump version to `0.0.12`
Resolves https://github.com/hobbyfarm/admin-ui/issues/14
> correct timestamp for availability from hh to HH

- src/app/configuration/environments/edit-environment/edit-environment.component.html
The build currently fails with the following error:
```
Step 3/10 : RUN $(npm bin)/ng build --prod --aot
---> Running in 08e43a1c0043
ERROR in src/app/configuration/environments/edit-environment/edit-environment.component.html(1,21): Property 'wizardOpen' does not exist on type 'EditEnvironmentComponent'.
src/app/configuration/environments/edit-environment/edit-environment.component.html(1,21): Property 'wizardOpen' does not exist on type 'EditEnvironmentComponent'.
```
This is due to setting the `clrWizardOpen` property and not using it (since the wizard is opened through other functionality).
> remove unused clrWizardOpen binding

- package-lock.json
- package.json
Fixes an issue where Angular 9 depends on fibers, but fibers will not work with Node 12 unless at version 4 or higher (python compilation and install errors using node-gyp).
> updated fibers to 4

- src/app/event/new-scheduled-event/new-scheduled-event.component.ts
This PR fixes an issue with editing scheduledevents. 
The Commit https://github.com/hobbyfarm/admin-ui/commit/19b474f3903903df5ede6027c5da500c24a722a9 brought in a check to verify that the Access Code does not already exists. However this was also applied for editing SEs which makes it impossible to edit SEs.
This PR fixes this check, so that the AC of the SE that we are currently editing is not considered a duplicate.
> Fix unique accesscode check

- src/app/header/header.component.html
This PR fixes the position for the top right menu in the header of the admin-ui. 
instead of
> Fix Menu Position

- src/app/data/scheduledevent.service.ts
- src/app/event/new-scheduled-event/new-scheduled-event.component.ts
Restricted Bind and On Demand options could not be updated.
Also they were always displayed as true in the UI when updating.
This PR adds some features so that these options will
1. display the correct state
2. be updated (At least when there are corresponding additions to gargantua)
> Update restricted bind and on demand for scheduledEvents

- src/app/data/scheduledevent.service.ts
- src/app/event/event.component.ts
- src/app/event/new-scheduled-event/new-scheduled-event.component.ts
This PR fixes https://github.com/hobbyfarm/hobbyfarm/issues/157
ScheduledeventService will now cache the Scheduledevents and can be observed for changes.
This was required by the bug described in https://github.com/hobbyfarm/hobbyfarm/issues/157 where the list of scheduledevents was out of date when deleting or creating a new event, thus allowing for duplicate access codes or marking access codes as duplicate when they are in fact not.
(This also saves one request every time the scheduledevent view is loaded)
> Change ScheduledeventService to cache SEs and make changes observable

- src/app/event/new-scheduled-event/new-scheduled-event.component.ts
This PR fixes https://github.com/hobbyfarm/hobbyfarm/issues/22
When creating a new SE in "advanced mode" all VM Types are shown, also if we only need some types for the scenarios we have selected before.
This PR changes the way VM types are displayed and only shows us the required templates.
> Only display relevant VM templates

- src/app/event/new-scheduled-event/new-scheduled-event.component.ts
This PR changes the way required VMs are calculated.
Before this change the number VMs required was calculated by simply adding up the VMs required by each scenario selected in a SE.
However a user can not start 2 scenarios at the same time thus creating overhead VMs when static provisioning VMs.
This PR changes the calculation, taking the highest count of VMs needed per template instead of just adding them up.
Example:
1st scenario needs 3x VM A
2nd scenario also needs 2x VM A and 1x VM B
Before this PR there were 6 VMs created: 5x A, 1x B
With this PR a count of 4 Vms is calculated: 3x A, 1x B as this is the maximum needed.
> Better calculation for required VMs

- src/app/scenario/scenario.component.html
This adds the documentation for glossary entries and CTR limitations to the admin-ui as requested in https://github.com/hobbyfarm/ui/pull/94#issuecomment-961404165
> Add Documentation for Glossary Entries and CTR limitations

- src/app/login/login.component.scss
The CSS Style for the admin logo was not adjusted and therefore was ignored. When using a large sized image, the image would be displayed at full width.
This fixes the ID in the CSS file
> Fix admin logo css style

- src/app/event/new-scheduled-event/new-scheduled-event.component.ts
When checking for Environment availability first you gather the list of environments, then POST an availability request based on start and end timestamps as well as the environment name.
In the New Event environment, the availability check makes a request based on the events display_name vs the name (which is the objectid). This results in a 500 error from gargantua as it cannot find the display_name
> Correct the New Event environment availability check to use the object-id vs display name

- src/app/configuration/configuration.component.html
This fixes the RBAC Directive for Virutalmachinetemplates. 
VMTemplates is not an allowed resource
> Fix RBAC Directive for virtualmachinetemplates

- src/app/app.module.ts
- src/app/configuration/environments/environment-detail/environment-detail.component.html
- src/app/configuration/environments/environment-detail/environment-detail.component.scss
- src/app/configuration/environments/environment-detail/environment-detail.component.ts
- src/app/configuration/environments/environments.component.html
- src/app/configuration/environments/environments.component.ts
- src/app/configuration/vmtemplates/edit-vmtemplate/edit-vmtemplate.component.html
- src/app/configuration/vmtemplates/vmtemplate-detail/vmtemplate-detail.component.html
- src/app/configuration/vmtemplates/vmtemplate-detail/vmtemplate-detail.component.scss
- src/app/configuration/vmtemplates/vmtemplate-detail/vmtemplate-detail.component.ts
- src/app/configuration/vmtemplates/vmtemplates.component.html
- src/app/configuration/vmtemplates/vmtemplates.component.ts
- src/app/data/environment.service.ts
- src/app/vmset/vmset.component.html
- Implements detail component for environments and vm templates if the user owns the corresponding GET permission
- Works with https://github.com/hobbyfarm/gargantua/pull/114
**Which issue(s) this PR fixes**: fixes [hobbyfarm/hobbyfarm#213](https://github.com/hobbyfarm/hobbyfarm/issues/213)
> Add details component for environments and vm templates

- src/app/configuration/environments/environment-detail/environment-detail.component.scss
- src/app/dashboards/vm-dashboard/vm-dashboard.component.ts
- src/styles.scss
- `::ng-deep` promotes component styles to global styles (https://angular.io/guide/component-styles). Prevent this effect by using `:host`
- fix typo
- improve rendering of modals
> Css and fixes

- src/app/configuration/environments/edit-environment/edit-environment.component.html
- src/app/configuration/environments/edit-environment/edit-environment.component.scss
- src/app/configuration/environments/edit-environment/edit-environment.component.ts
- src/app/configuration/environments/environment-detail/environment-detail.component.html
- src/app/configuration/environments/environment-detail/environment-detail.component.ts
- src/app/configuration/vmtemplates/edit-vmtemplate/edit-vmtemplate.component.html
- src/app/configuration/vmtemplates/edit-vmtemplate/edit-vmtemplate.component.ts
- src/app/configuration/vmtemplates/vmtemplate-detail/vmtemplate-detail.component.html
- src/app/dashboards/vm-dashboard/vm-dashboard.component.html
- src/app/dashboards/vm-dashboard/vm-dashboard.component.ts
- src/app/data/environment.service.ts
- src/app/data/environment.ts
- src/app/data/environmentavailability.ts
- src/app/data/vmtemplate.service.ts
- src/app/data/vmtemplate.ts
- src/app/event/new-scheduled-event/new-scheduled-event.component.html
- src/app/event/new-scheduled-event/new-scheduled-event.component.ts
Needed by https://github.com/hobbyfarm/gargantua/pull/130
> Remove Burst, RAW Capacity

- src/app/configuration/vmtemplates/edit-vmtemplate/edit-vmtemplate.component.html
- src/app/configuration/vmtemplates/edit-vmtemplate/edit-vmtemplate.component.scss
- src/app/configuration/vmtemplates/edit-vmtemplate/edit-vmtemplate.component.ts
Fix [284](https://github.com/hobbyfarm/hobbyfarm/issues/284)
> Add information if cloud-config is empty

- .github/workflows/ci.yaml
Node throws error while building due to openssl being used. Provide the flag to let the build pass
> Add openssl-legaxy-provider flag

- src/app/app.module.ts
- src/app/configuration/code-with-syntax-highlighting/code-with-syntax-highlighting.component.html
- src/app/configuration/code-with-syntax-highlighting/code-with-syntax-highlighting.component.scss
- src/app/configuration/code-with-syntax-highlighting/code-with-syntax-highlighting.component.spec.ts
- src/app/configuration/code-with-syntax-highlighting/code-with-syntax-highlighting.component.ts
- src/app/configuration/vmtemplates/edit-vmtemplate/edit-vmtemplate.component.html
- src/app/configuration/vmtemplates/edit-vmtemplate/edit-vmtemplate.component.scss
- src/app/configuration/vmtemplates/edit-vmtemplate/edit-vmtemplate.component.ts
- src/app/configuration/vmtemplates/edit-vmtemplate/vmtemplate-service-form/vmtemplate-service-form.component.html
Adds syntax Highlighting via Prism for the Clud-Init-Config Editor in Edit VM-Templates.
Corresponding Issue: [283](https://github.com/hobbyfarm/hobbyfarm/issues/283)
> Syntax highlighhting for cloud config

- src/app/session-statistics/session-statistics.component.html
- src/app/session-statistics/session-statistics.component.scss
- src/app/session-statistics/session-statistics.component.ts
Updates https://github.com/hobbyfarm/admin-ui/pull/147.
- scenarios shown in the session statistic chart can now be prefiltered
- scenarios shown in the session statistic data grid are now sorted by number of total sessions
- moved the signposts for updating start/end date back to the default position
> Chart update

- src/app/data/vmtemplate.service.ts
With this PR config maps of VMTemplates containing the character ';' can be saved. This includes cloud init data for Services
> Fix cloud init not saved

- src/app/configuration/code-with-syntax-highlighting/code-with-syntax-highlighting.component.html
- src/app/configuration/code-with-syntax-highlighting/code-with-syntax-highlighting.component.scss
- src/app/configuration/code-with-syntax-highlighting/code-with-syntax-highlighting.component.ts
Fixes the issue that the Code Editor with syntax highlighting does not handle Input that grows over its initial size on its own.
> Auto adjust height of code editor

- src/app/event/new-scheduled-event/new-scheduled-event.component.ts
Sometimes if an environment does not support multiple VMTs, it is shown multiple times in the list of non supported environments
> Fix bug where invalid environments are shown multiple times

- src/app/configuration/vmtemplates/edit-vmtemplate/vmtemplate-service-form/vmtemplate-service-form.component.html
- src/app/configuration/vmtemplates/edit-vmtemplate/vmtemplate-service-form/vmtemplate-service-form.component.ts
This PR makes it possible to for the User to change the Order in which Services/Webinterfaces are processed for a VMTemplate. This leads to Control over the resulting Cloud Config without having to delete Services/Webinterfaces just to create them again in the desired Order.
> implement order functionality

- src/app/configuration/environments/edit-environment/edit-environment.component.html
- src/app/configuration/environments/edit-environment/edit-environment.component.ts
- src/app/configuration/environments/environment-detail/environment-detail.component.html
- src/app/configuration/environments/environment-detail/environment-detail.component.ts
While editing environments, the ID of VMT is used where we could have used the name. This PR Changes this behaviour
> Display Name of VMT instead of id

- package-lock.json
- package.json
- src/app/data/otac.type.ts
- src/app/data/scheduledevent.service.ts
- src/app/event/otacmanagement/otacmanagement.component.html
- src/app/event/otacmanagement/otacmanagement.component.scss
- src/app/event/otacmanagement/otacmanagement.component.ts
- It adds all changes needed to display the duration, introducing a new status label "out-of-time" as well as allowing the admin to set the duration when creating OTACs.
See:
- Modifying any existing duration is not yet part of this implementation as this might not be needed
- Added https://www.npmjs.com/package/parse-duration to parse time durations like "1d20m"
- Changed CSV export to print duration as well as the current status
This PR comes along with https://github.com/hobbyfarm/gargantua/pull/177
> Modify OTAC Modal to handle durations

- src/app/dashboards/progress-dashboard/progress-dashboard.component.ts
When the user is not in the local cached users list "None" will be displayed. Same for the scenario name. 
It is easier when the user id and scenari ids are displayed.
> Display user and scenario id instead of None

- src/app/app.module.ts
- src/app/dashboards/progress-dashboard/progress-dashboard.component.html
- src/app/dashboards/progress-dashboard/progress-dashboard.component.ts
Add button that exports the session data as CSV
fixes https://github.com/hobbyfarm/hobbyfarm/issues/418
> Export session data

- src/app/session-statistics/session-time-statistics/session-time-statistics.component.html
- src/app/session-statistics/session-time-statistics/session-time-statistics.component.ts
Someimes the mean is not very helpful and we need the median:
> Add median to chart about scenarios

- src/app/dashboards/progress-dashboard/progress-dashboard.component.html
- src/app/dashboards/progress-dashboard/progress-dashboard.component.ts
- src/app/progress/progress.component.html
- src/app/progress/progress.component.ts
fixes https://github.com/hobbyfarm/hobbyfarm/issues/425
Adds a "hide usernames" button to the progress dashboard to allow screensharing without providing usernames. When the toggle is enabled the user id will be shown instead.
> Add hide usernames button to dashboard for privacy on screensharings

- src/app/data/course.service.ts
- src/app/unicode.ts
Use and improve existing atou and utoa functions for unicode handling in course information.
fixes https://github.com/hobbyfarm/hobbyfarm/issues/417
> Fix handling umlauts in Course title and description

- src/app/configuration/vmtemplates/edit-vmtemplate/vmtemplate-service-form/vmtemplate-service-form.component.html
- src/app/configuration/vmtemplates/edit-vmtemplate/vmtemplate-service-form/vmtemplate-service-form.component.ts
- src/app/data/predefinedservice.service.ts
- src/app/data/protocol.ts
- src/app/data/vm-template-service-configuration.ts
This PR implements two new proxy options, specifying a protocol (http or https) and disabling the Authorization Header for proxied requests.
> Add new proxy configuration options

- src/app/configuration/settings/settings.component.html
- src/app/configuration/settings/settings.component.ts
Now a success message is shown by changing admin configurations. Instead of the AlertComponent another alert type was used, that had no function "success". Now the correct type is used and die message is displayed
> Fix for Issue 468 - no success message on changing admin configurations
