src/app/data/scenario.service.ts

Test encoding fix

---

src/app/event/event.component.html

event status

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/data/user.service.spec.ts
src/app/data/user.service.ts
src/app/data/user.ts
src/app/header/header.component.html
src/app/user-email-filter.spec.ts
src/app/user-email-filter.ts
src/app/user-id-filter.spec.ts
src/app/user-id-filter.ts
src/app/user/user/user.component.html
src/app/user/user/user.component.spec.ts
src/app/user/user/user.component.ts

Allow for editing of users including admin flag and access codes

User editing

---

src/app/data/environment.ts
src/app/event/new-scheduled-event/new-scheduled-event.component.ts

Fixing vm whack-a-mole issue

---

src/app/data/environmentavailability.ts
src/app/event/new-scheduled-event/new-scheduled-event.component.html
src/app/event/new-scheduled-event/new-scheduled-event.component.scss
src/app/event/new-scheduled-event/new-scheduled-event.component.ts

Validation for VM counts during ScheduledEvent creation

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/configuration/configuration.component.html
src/app/configuration/configuration.component.spec.ts
src/app/configuration/configuration.component.ts
src/app/configuration/environments/environments.component.html
src/app/configuration/environments/environments.component.spec.ts
src/app/configuration/environments/environments.component.ts
src/app/configuration/environments/new-environment/new-environment.component.html
src/app/configuration/environments/new-environment/new-environment.component.scss
src/app/configuration/environments/new-environment/new-environment.component.spec.ts
src/app/configuration/environments/new-environment/new-environment.component.ts
src/app/data/environment.service.ts
src/app/data/environment.ts
src/app/header/header.component.html

- Added configuration section to admin ui
- Added ability to create new environments (pending gargantua integration)

Configuration section and environment creation

---

entrypoint.sh
src/app/app.module.ts
src/app/data/environment.service.ts
src/app/data/scenario.service.ts
src/app/data/scheduledevent.service.ts
src/app/data/user.service.ts
src/app/data/vmtemplate.service.ts
src/app/login/login.component.ts
src/environments/environment.ts

Ability to communicate with the api server insecurely

insecure api capability

---

src/app/event/new-scheduled-event/new-scheduled-event.component.html
src/app/event/new-scheduled-event/new-scheduled-event.component.ts

This should fix https://github.com/hobbyfarm/hobbyfarm/issues/32. I've updated the access code validation regex to match that error message and added some text to explain the regex (I removed printing the actual regex because I think it'd just be more confusing to see it).

update access code validation pattern

---

.gitignore
src/app/app.module.ts
src/app/data/virtualmachine.ts
src/app/event/event.component.html
src/app/event/event.component.ts
src/app/event/new-scheduled-event/new-scheduled-event.component.html
src/app/event/new-scheduled-event/new-scheduled-event.component.ts
src/app/scenario/scenario.component.html
src/app/scenario/scenario.component.ts
src/environments/environment.ts
src/styles.scss

* Added helper text for defining markdown
* Added filtering and sorting for scheduled events
* Added "simple mode" for scheduled event provisioning.

quality of life changes

---

.dockerignore
.env.example
.github/workflows/main.yaml
.gitignore
CONTRIBUTING.md
README.md
angular.json
cicd/docker-local/Dockerfile
cicd/docker-local/stage/etc/fixuid/config.yml
cicd/docker-local/stage/usr/local/bin/run.sh
cicd/docker/Dockerfile
cicd/docker/docker-compose-release.yaml
cicd/docker/docker-compose-sdk.yaml
cicd/docker/stage-release/etc/nginx/conf.d/default.conf
cicd/docker/stage-release/usr/local/bin/entrypoint.sh
compose.sh
docker-compose.yaml
package.json
setup-local.js
src/environments/.gitignore
src/environments/environment.local.example.ts

Related to https://github.com/hobbyfarm/hobbyfarm/issues/78
same as https://github.com/hobbyfarm/ui/pull/59
To modify Angular environment variables for your local environment, copy `src/environments/environment.local.example.ts` to `src/environments/environment.example.ts` and update variables as needed.
```
npm install
npm run start:local
```
The Angular server will start a watch loop and listen on [localhost:4200](http://localhost:4200).
```
./compose-up.sh
./compose-up.sh --build
```
`./compose-up.sh` does the following:
- calls `docker-compose up`
- creates or starts the `hf-admin-ui` container, runs `npm install` and starts the Angular Server, re-builds on change, and listens on [localhost:16205](http://localhost:16205)
If `pakcages.json` has changed, stop and restart the …

WIP: Admin UI Local Development and CI Improvements

---

src/app/data/course.service.ts
src/app/data/course.ts
src/app/data/scheduledevent.service.ts
src/app/data/scheduledevent.ts
src/app/event/event.component.html
src/app/event/new-scheduled-event/new-scheduled-event.component.html
src/app/event/new-scheduled-event/new-scheduled-event.component.scss
src/app/event/new-scheduled-event/new-scheduled-event.component.ts
src/styles.scss

@ebauman, these changes allow creating scheduled events with courses. It's still a WIP because it sort of kicks scenarios to 2nd class objects as it is (e.g., can't make events with just scenarios :disappointed:) and doesn't allow editing courses in the same way that scenarios can be.
Anyway, just wanted to push it up and get it in front of you and whenever one of us finds the time we can make updates.

Course object

---

src/app/app.module.ts

fixed jwt dynamic loading issue

---

src/app/atob.pipe.ts
src/app/data/course.service.ts
src/app/data/environment.service.ts
src/app/data/scenario.service.ts
src/app/data/scheduledevent.service.ts
src/app/data/user.service.ts
src/app/data/vmtemplate.service.ts
src/app/unicode.ts

unicode fixes

---

src/app/data/scenario.service.ts

missed some btoas

---

src/app/data/scenario.service.ts

Fixed utoa import

---

src/app/app.module.ts
src/app/event/event-status-filter/event-status-filter.component.html
src/app/event/event-status-filter/event-status-filter.component.spec.ts
src/app/event/event-status-filter/event-status-filter.component.ts
src/app/event/event.component.html

added finished status filtering

---

src/app/configuration/environments/edit-environment/edit-environment.component.ts

fixed null map issue

---

src/app/event/new-scheduled-event/new-scheduled-event.component.ts

Fix next button

---

src/app/data/scheduledevent.service.ts
src/app/data/scheduledevent.ts
src/app/event/new-scheduled-event/new-scheduled-event.component.html
src/app/event/new-scheduled-event/new-scheduled-event.component.ts

Allows users to schedule VMs on-demand instead of pre-creating.

Added on-demand functionality for scheduled events

---

src/app/event/new-scheduled-event/new-scheduled-event.component.ts

Change on_demand default to false

---

src/app/data/user.service.ts
src/app/user/edit-user/edit-user.component.html
src/app/user/edit-user/edit-user.component.ts
src/app/user/user/user.component.html

Adds button and confirmation popup for deletion of users. 
Done in concert with https://github.com/hobbyfarm/gargantua/pull/79

Allow for deletion of users

---

package-lock.json
package.json
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/data/scenario.service.ts
src/app/printable/printable.component.html
src/app/printable/printable.component.spec.ts
src/app/printable/printable.component.ts
src/app/scenario/scenario.component.html

Added button and new page to print scenarios. This was supported in the API, now exposed in the UI.

Ability to print scenarios from UI

---

src/app/alert/alert.component.html
src/app/alert/alert.component.spec.ts
src/app/alert/alert.component.ts
src/app/app.module.ts

created reusable alerting component that can be embedded in other components.
exposes methods success, error, warning, and info for simple usage of alerting.

Created alert component

---

src/app/alert/alert.component.ts
src/app/clr-alert-type.ts

see https://github.com/vmware/clarity/blob/v5/projects/angular/src/emphasis/alert/utils/alert-types.ts

error is now "danger" in clralerttype

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/configuration/configuration.component.html
src/app/configuration/vmtemplates/edit-vmtemplate/edit-vmtemplate.component.html
src/app/configuration/vmtemplates/edit-vmtemplate/edit-vmtemplate.component.spec.ts
src/app/configuration/vmtemplates/edit-vmtemplate/edit-vmtemplate.component.ts
src/app/configuration/vmtemplates/vmtemplates.component.html
src/app/configuration/vmtemplates/vmtemplates.component.spec.ts
src/app/configuration/vmtemplates/vmtemplates.component.ts
src/app/data/vmtemplate.service.ts
src/styles.scss

adds crud for vm templates to the configuration section of the admin ui

virtual machine template functionality

---

src/app/event/new-scheduled-event/new-scheduled-event.component.html
src/app/event/new-scheduled-event/new-scheduled-event.component.ts

* Fix access_code regex to not contain spaces
* Add validator to ensure an access_code is unique
* Add filters for scenario/course tables on name and description fields

Improve new scheduled event dialog

---

src/app/course/course-form/course-form.component.html
src/app/course/course-form/course-form.component.ts
src/app/course/course.component.html
src/app/course/course.component.ts
src/app/course/new-course/new-course.component.ts
src/app/data/course.service.ts
src/app/data/course.ts
src/app/data/scenario.service.ts
src/app/data/scenario.ts
src/app/event/new-scheduled-event/new-scheduled-event.component.ts
src/app/scenario/scenario.component.html
src/app/scenario/scenario.component.ts

Backend functionality for https://github.com/hobbyfarm/gargantua/pull/89
Categories and tags can be updated in the admin-ui
Also fixes https://github.com/hobbyfarm/hobbyfarm/issues/162

Categories and Tags for Scenarios

---

src/app/data/scheduledevent.service.ts
src/app/data/scheduledevent.ts
src/app/event/new-scheduled-event/new-scheduled-event.component.html
src/app/event/new-scheduled-event/new-scheduled-event.component.ts

Allow users to enable/disable pdf print functionality when creating/editing events.
**Which issue(s) this PR fixes**:
https://github.com/hobbyfarm/hobbyfarm/issues/142

Allow users to save scenario content as pdf

---

src/app/utils.ts

Fixes https://github.com/hobbyfarm/hobbyfarm/issues/187

Choose how many places of the time since should be shown

---

src/app/home/home.component.ts

Simpler and more performant refresh method for the home component.
CC @PhPrinz

refactor(home): simplify refresh method

---

src/app/event/new-scheduled-event/new-scheduled-event.component.html
src/app/event/new-scheduled-event/new-scheduled-event.component.ts

Fixes https://github.com/hobbyfarm/hobbyfarm/issues/17

Check for SE name uniqueness

---

src/app/event/event.component.ts
src/app/event/new-scheduled-event/new-scheduled-event.component.html
src/app/event/new-scheduled-event/new-scheduled-event.component.ts

This PR will make the SE wizard navigation skippable if an SE is edited.
Also fixes small bug with advanced page when editin SEs.
Fixes https://github.com/hobbyfarm/hobbyfarm/issues/164

Make SE wizard navigation better

---

.github/workflows/main.yaml
cicd/docker/docker-compose-release.yaml
cicd/docker/docker-compose-sdk.yaml

Replicates https://github.com/hobbyfarm/ui/pull/127 w/out the changes to `Dockerfile`

Slim down GH Actions CI

---

src/app/app-config.service.ts
src/app/configuration/roles/roles/roles.component.html
src/app/configuration/roles/roles/roles.component.ts
src/app/course/course.component.html
src/app/course/course.component.ts
src/app/data/rbac.service.ts
src/app/data/rbac.ts
src/app/directives/clarity-disable-selection.directive.ts
src/app/directives/rbac.directive.ts
src/app/header/header.component.ts
src/app/home/home.component.ts
src/app/login/login.component.ts
src/app/scenario/scenario.component.ts
src/app/user/user/user.component.html
src/app/user/user/user.component.ts
src/app/vmset/vmset.component.ts

Fix ts compile errors

---

src/app/event/new-scheduled-event/new-scheduled-event.component.html

Fixes https://github.com/hobbyfarm/hobbyfarm/issues/199

fix deselection by filtering of scenarios/courses during event creation or editing

---

src/app/configuration/environments/edit-environment/edit-environment.component.html
src/app/configuration/environments/edit-environment/edit-environment.component.ts
src/app/configuration/vmtemplates/edit-vmtemplate/edit-vmtemplate.component.html
src/app/configuration/vmtemplates/edit-vmtemplate/edit-vmtemplate.component.ts
src/app/data/vmtemplate.service.ts
src/app/data/vmtemplate.ts
src/app/event/new-scheduled-event/new-scheduled-event.component.html

When editing environments, you can now only select available VMTs - which is also much easier now
Needs https://github.com/hobbyfarm/gargantua/pull/110

Rename CountMap to ConfigMap, rework vmt selection in environment

---

src/app/data/user.service.ts
src/app/data/user.ts
src/app/user/edit-access-codes/edit-access-codes.component.ts
src/app/user/edit-user/edit-user.component.html
src/app/user/edit-user/edit-user.component.ts

Remove the admin toggle setting for the user list. This is unused wit hthe new RBAC changes

Remove Admin Flag from Admin-UI in favor of RBAC

---

src/app/configuration/roles/rule-form/rule-form.component.ts
src/app/course/course.component.html
src/app/course/course.component.ts
src/app/data/course.service.ts
src/app/data/rbac.service.ts
src/app/data/rbac.ts
src/app/data/role.ts
src/app/directives/rbac.directive.ts
src/app/header/header.component.ts
src/app/home/home.component.ts
src/app/scenario/scenario.component.ts
src/app/vmset/new-vm/new-vm.component.html
src/app/vmset/new-vm/new-vm.component.ts
src/app/vmset/vmset.component.html
src/app/vmset/vmset.component.ts

- Fixes 403 Errors for Content Management
- Adds some typings

Prevent authorization errors

---

src/app/configuration/environments/edit-environment/edit-environment.component.ts
src/app/configuration/environments/environments.component.ts
src/app/configuration/vmtemplates/vmtemplates.component.html
src/app/configuration/vmtemplates/vmtemplates.component.ts
src/app/course/course-form/course-form.component.ts
src/app/course/course.component.html
src/app/course/course.component.ts
src/app/data/course.service.ts
src/app/data/course.ts
src/app/event/event.component.html
src/app/event/event.component.ts
src/app/event/new-scheduled-event/new-scheduled-event.component.ts
src/app/header/header.component.ts
src/app/vmset/new-vm/new-vm.component.ts
src/app/vmset/vmset.component.html
src/app/vmset/vmset.component.ts

Multiple bug fixes and code quality improvements

---

src/app/vmset/new-vm/new-vm.component.html
src/app/vmset/vmset.component.html
src/app/vmset/vmset.component.ts

Fixes https://github.com/hobbyfarm/hobbyfarm/issues/225

Fix add button for vms in courses

---

src/app/event/new-scheduled-event/new-scheduled-event.component.html
src/app/event/new-scheduled-event/new-scheduled-event.component.ts

fixes https://github.com/hobbyfarm/hobbyfarm/issues/219

Display error message if no suitable environment found during event creation

---

src/app/course/course.component.ts

fixes https://github.com/hobbyfarm/hobbyfarm/issues/200

Update course list after creation and deletion

---

src/app/header/header.component.ts

Fixes https://github.com/hobbyfarm/hobbyfarm/issues/226

Logout user after token expiration

---

src/app/header/header.component.ts

Fixes issue introduced in https://github.com/hobbyfarm/ui/pull/141

Fix logout time

---

src/app/course/course.component.html
src/app/course/course.component.ts
src/app/scenario/scenario.component.html
src/app/scenario/scenario.component.scss
src/app/scenario/scenario.component.ts

closes https://github.com/hobbyfarm/hobbyfarm/issues/232

Filter-scenarios based on categories

---

.github/workflows/main.yaml

to prevent pipeline failing on new release

Tag latest image

---

src/app/app.module.ts
src/app/configuration/vmtemplates/edit-vmtemplate/vmtemplate-service-form/vmtemplate-service-form.component.html
src/app/configuration/vmtemplates/edit-vmtemplate/vmtemplate-service-form/vmtemplate-service-form.component.scss
src/app/configuration/vmtemplates/edit-vmtemplate/vmtemplate-service-form/vmtemplate-service-form.component.ts
src/app/data/predefinedservice.service.ts
src/app/data/vm-template-service-configuration.ts

Settings for Header / Path rewriting + Disallow iFrame

Settings for WebServices

---

src/app/app.module.ts
src/app/configuration/code-with-syntax-highlighting/code-with-syntax-highlighting.component.html
src/app/configuration/code-with-syntax-highlighting/code-with-syntax-highlighting.component.scss
src/app/configuration/code-with-syntax-highlighting/code-with-syntax-highlighting.component.ts
src/app/directives/resizable-text-area.directive.ts

Fixes the behavior of 'code editor' input fields when resized by the user.

react on size changes to textinput

---

src/app/data/vm-template-service-configuration.ts

Cloud Init Configuration in YAML with nested Fields caused the Admin-UI to not save the configuration at all. This PR Fixes that.

Handle nested cloud config fields

---

src/app/configuration/vmtemplates/edit-vmtemplate/edit-vmtemplate.component.html
src/app/configuration/vmtemplates/edit-vmtemplate/edit-vmtemplate.component.ts
src/app/configuration/vmtemplates/vmtemplate-detail/vmtemplate-detail.component.html
src/app/configuration/vmtemplates/vmtemplate-detail/vmtemplate-detail.component.scss
src/app/configuration/vmtemplates/vmtemplate-detail/vmtemplate-detail.component.ts

With this PR the Output of (Web-)Services and the resulting cloud-config is easier to read during editing as well as in the VM-Template Overview.

293 prettier output for services cloud config

---

src/app/content/content.component.ts

The Content Management when it's empty should navigate to the Either Scenarios or Course if they are available

Content Management #312

---

src/app/scenario/md-editor/md-editor.component.html

fixes https://github.com/hobbyfarm/hobbyfarm/issues/324

make sure to open Syntax Reference in a new window

---

src/app/dashboards/progress-dashboard/progress-dashboard.component.ts
src/app/data/course.service.ts
src/app/data/environmentavailability.ts
src/app/data/scenario.service.ts
src/app/data/user.service.ts
src/app/event/new-scheduled-event/new-scheduled-event.component.ts
src/app/scenario/scenario.component.ts
src/app/user/user/user.component.html
src/app/user/user/user.component.ts

fixes https://github.com/hobbyfarm/hobbyfarm/issues/326
fixes https://github.com/hobbyfarm/hobbyfarm/issues/329
fixes https://github.com/hobbyfarm/hobbyfarm/issues/330

Improvements for VMT limits, Scenario list

---

src/app/app.module.ts
src/app/data/otac.type.ts
src/app/data/scheduledevent.service.ts
src/app/event/event.component.html
src/app/event/event.component.ts
src/app/event/otacmanagement/otacmanagement.component.html
src/app/event/otacmanagement/otacmanagement.component.scss
src/app/event/otacmanagement/otacmanagement.component.ts

What this PR does / why we need it:
Introduces a UI to manage AccessCodes that can only be used once.
Which issue(s) this PR fixes:
fixes https://github.com/hobbyfarm/hobbyfarm/issues/322
Depends on changes to Gargantua made in https://github.com/hobbyfarm/gargantua/pull/150

Otac management

---

src/app/user/edit-user/edit-user.component.html

Display user id when editing user

---

src/app/user-accescode-filter.ts
src/app/user-email-filter.ts

fixes https://github.com/hobbyfarm/hobbyfarm/issues/361

Fix user filter by only comparing lowercase values

---

src/app/configuration/environments/environments.component.html
src/app/configuration/roles/roles/roles.component.html
src/app/configuration/vmtemplates/vmtemplates.component.html
src/app/event/event.component.html
src/app/event/new-scheduled-event/new-scheduled-event.component.html
src/app/event/new-scheduled-event/new-scheduled-event.component.ts

Also display the name of the VMTemplate and not the id (see that there are spaces etc.)
fixes https://github.com/hobbyfarm/hobbyfarm/issues/340

Improve Simple mode by showing VM Counts

---

src/app/event/new-scheduled-event/new-scheduled-event.component.ts

fix problem with VM value with edit mode on final page

Issue339 new scheduled event

---

src/app/configuration/environments/edit-environment/edit-environment.component.html
src/app/configuration/environments/edit-environment/edit-environment.component.scss
src/app/configuration/environments/edit-environment/edit-environment.component.ts

add view changes in edit mode configuration/environment

Issue339 configuration

---

src/app/course/course-wizard/course-wizard.component.html
src/app/course/course-wizard/course-wizard.component.scss
src/app/course/course-wizard/course-wizard.component.ts

Add color when edit parameters of course

Issue339 content courses

---

src/app/data/user.ts
src/app/user/edit-user/edit-user.component.html
src/app/user/edit-user/edit-user.component.ts

https://github.com/hobbyfarm/gargantua/pull/182 is needed

Display last login date and registered date

---

src/app/user/edit-user/edit-user.component.ts

fixes https://github.com/hobbyfarm/hobbyfarm/issues/347

Reset form after updating a users password

---

src/app/data/scenario.service.ts
src/app/filter-scenarios/filter-scenarios.component.ts

Fixes https://github.com/hobbyfarm/hobbyfarm/issues/364
fixes https://github.com/hobbyfarm/hobbyfarm/issues/378

Update category filter when scenarios update

---

src/app/course/course-wizard/course-wizard.component.html
src/app/course/course-wizard/course-wizard.component.scss
src/app/course/course-wizard/course-wizard.component.ts
src/app/vmset/new-vm/new-vm.component.html
src/app/vmset/new-vm/new-vm.component.ts
src/app/vmset/vmset.component.html

Add validator to check unique VM name when create VM in course

Add validator to check unique VM name when create VM in course

---

package-lock.json
package.json
src/app/step/hf-markdown.component.ts

This PR adjusts the ngx-markdown renderer to align with the UI again.
Adds mermaid-js
Fixes some bugs with the syntax highlighting

Add mermaid-js to admin-ui

---

src/app/app-routing.module.ts
src/app/configuration/configuration.component.html
src/app/configuration/configuration.component.ts
src/app/configuration/environments/edit-environment/edit-environment.component.ts
src/app/configuration/environments/environment-detail/environment-detail.component.ts
src/app/configuration/settings/settings.component.html
src/app/configuration/settings/settings.component.ts
src/app/content/content.component.ts
src/app/course/course-wizard/course-wizard.component.ts

Add scopes to configuration menu

---

src/app/dashboards/dashboard-details/dashboard-details.component.html
src/app/dashboards/dashboard-details/dashboard-details.component.ts
src/app/data/progress.service.ts
src/app/session-statistics/session-statistics.component.html
src/app/session-statistics/session-statistics.component.ts

Add the graphes from the home component to the ScheduledEvent so that we can show view statistics for any SE

Add Statistics to Event tabs

---

src/app/app.module.ts
src/app/session-statistics/session-statistics.component.html
src/app/session-statistics/session-statistics.component.ts
src/app/session-statistics/session-time-statistics/session-time-statistics.component.html
src/app/session-statistics/session-time-statistics/session-time-statistics.component.ts
src/app/utils.ts

Improve chart by caching progresses, add chart for average step duration inside scenario

---

src/app/dashboards/dashboards.component.ts

fixes https://github.com/hobbyfarm/hobbyfarm/issues/426
In the dashboard view open the SE from the URL if given, otherwise select the first one

 Open the SE from url and not select the first one

---

src/app/event/event.component.html

fixes https://github.com/hobbyfarm/hobbyfarm/issues/435

Rename button from new new to new

---

src/app/event/otacmanagement/otacmanagement.component.html

fixes https://github.com/hobbyfarm/hobbyfarm/issues/452

Make OTAC fiterable

---

src/app/event/otacmanagement/otacmanagement.component.ts

fixes https://github.com/hobbyfarm/hobbyfarm/issues/474

Also export user id to otac export

---

README.md
angular.json
src/app/configuration/settings/settings.component.html
src/app/configuration/settings/settings.component.ts
src/index.html

Added the possibility to use custom css to the admin ui.

Issue 382 custom css

---

src/app/data/rbac.service.ts

fix rbac role issue 

---

src/app/data/scenario.service.ts
src/app/scenario/scenario.component.html
src/app/scenario/scenario.component.ts

This PR adds a button to invoke the existing clone endpoint (/a/scenario/copy/{id}) via the admin ui.

Added button for cloning scenarios 

---

src/app/event/new-scheduled-event/new-scheduled-event.component.html

fixes https://github.com/hobbyfarm/hobbyfarm/issues/479

Fix 479: Adjust comparison between two booleans

---

src/app/configuration/vmtemplates/edit-vmtemplate/edit-vmtemplate.component.ts
src/app/configuration/vmtemplates/vmtemplates.component.ts
src/app/course/course-wizard/course-wizard.component.ts
src/app/course/course.component.ts
src/app/scenario/scenario.component.ts

Part of https://github.com/hobbyfarm/hobbyfarm/issues/478

478: Fix Error message for many requests

---

package-lock.json
package.json
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/configuration/vmtemplates/edit-vmtemplate/edit-vmtemplate.component.html
src/app/configuration/vmtemplates/edit-vmtemplate/edit-vmtemplate.component.ts
src/app/configuration/vmtemplates/vmtemplate-detail/vmtemplate-detail.component.html
src/app/cost-statistics/cost-dashboard.component.html
src/app/cost-statistics/cost-dashboard.component.scss
src/app/cost-statistics/cost-dashboard.component.ts
src/app/dashboards/cost-dashboard/cost-dashboard.component.html
src/app/dashboards/cost-dashboard/cost-dashboard.component.scss
src/app/dashboards/cost-dashboard/cost-dashboard.component.ts
src/app/dashboards/cost-dashboard/monthly-cost-chart/monthly-cost-chart.component.html
src/app/dashboards/cost-dashboard/monthly-cost-chart/monthly-cost-chart.component.ts
src/app/dashboards/dashboard-details/dashboard-details.component.html
src/app/dashboards/dashboard-details/dashboard-details.component.ts
src/app/dashboards/progress-dashboard/progress-dashboard.component.ts
src/app/data/cost.service.ts
src/app/data/cost.ts
src/app/data/forms.ts
src/app/data/settings.service.ts
src/app/data/vmtemplate.service.ts
src/app/data/vmtemplate.ts
src/app/header/header.component.html
src/app/header/header.component.ts
src/app/home/home.component.html
src/app/validators/eitherallornone.validator.ts
src/app/validators/float.validator.ts

Adapt VMTemplate dialog to support cost-tracking.
This pr depends on
https://github.com/hobbyfarm/gargantua/pull/212
https://github.com/hobbyfarm/hobbyfarm/pull/484
**Which issue(s) this PR fixes**:
Usage: Fixes https://github.com/hobbyfarm/hobbyfarm/issues/483

add cost tracking properties for vmtemplate

---

src/styles.scss

The progress bar for status "running" was not displayed anymore. Now the status-running color is set again.

Fixed the progress bar color in progress dashboard

---

src/app/step/hf-markdown.component.scss

#489 set markdown image size to max-image-size

---

src/app/course/course-form/course-form.component.html
src/app/course/course-form/course-form.component.ts
src/app/course/course-wizard/course-wizard.component.html
src/app/course/course-wizard/course-wizard.component.ts
src/app/data/course.service.ts
src/app/data/course.ts
src/app/data/forms.ts
src/app/step/step-component/step.component.scss
src/app/step/step-component/step.component.ts
src/app/validators/url.validator.ts

**What this PR does / why we need it:**
Makes Course configurable as Learningpath
Adds UI Element to add Course to Catalog
**Which issue(s) this PR fixes:**
fixes https://github.com/hobbyfarm/hobbyfarm/issues/390

Add UI elements for new course infos

---

src/app/data/scheduledevent.service.ts

Fixes https://github.com/hobbyfarm/hobbyfarm/issues/486

fix: update path to delete SE
